<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../selectAccounts.wsdl"/>
      <rootElement name="selectAccountsOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selectAccounts"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/core/ebs/cs.pay.ebs.Accounts_1.0.wsdl"/>
      <rootElement name="uploadAccount" namespace="http://www.AlMajdouie.sa/ebs/cs.pay.Accounts"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [TUE MAY 19 10:44:47 AST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns2="http://www.AlMajdouie.sa/ebs/cs.pay.ebs.Accounts/types"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://www.AlMajdouie.sa/ebo/util.cmn.EBMHeader"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns0="http://www.AlMajdouie.sa/ebs/cs.pay.ebs.Accounts"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:waseu="http://www.AlMajdouie.sa/ebo/util.flt.Fault"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:wasec="http://www.AlMajdouie.sa/ebs/cs.pay.Accounts"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="http://www.AlMajdouie.sa/ebo/util.cmn.Basic"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/selectAccounts"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/cs.pay.application/cs.pay.Accounts/selectAccounts"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl db xsd tns ns2 soap12 ns1 soap ns0 mime waseu wasec ns3 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <wasec:uploadAccount>
      <wasec:header>
        <ns1:rquid>
          <xsl:value-of select="/db:selectAccountsOutputCollection/db:selectAccountsOutput/db:ACC_REQ_ID"/>
        </ns1:rquid>
      </wasec:header>
      <wasec:body>
        <wasec:clientDate>
          <xsl:value-of select="/db:selectAccountsOutputCollection/db:selectAccountsOutput/db:REQ_DATE"/>
        </wasec:clientDate>
        <xsl:for-each select="/db:selectAccountsOutputCollection/db:selectAccountsOutput">
          <wasec:accountInfo>
            <wasec:billingAccount>
              <xsl:value-of select="db:ACCOUNT_NUMER"/>
            </wasec:billingAccount>
            <xsl:if test='db:STATUS_CODE = "SUBMITTED"'>
              <wasec:accountStatusCode>
                <xsl:text disable-output-escaping="no">AcctNew</xsl:text>
              </wasec:accountStatusCode>
            </xsl:if>
            <wasec:beneficiaryId>
              <wasec:officialId>
                <xsl:value-of select="db:CUST_OFFICIAL_ID"/>
              </wasec:officialId>
              <wasec:officialIdType>
                <xsl:value-of select="db:OFFICIAL_ID_TYPE"/>
              </wasec:officialIdType>
            </wasec:beneficiaryId>
          </wasec:accountInfo>
        </xsl:for-each>
      </wasec:body>
    </wasec:uploadAccount>
  </xsl:template>
</xsl:stylesheet>
