<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../cs_pay_cvs_uploadBill.wsdl"/>
      <rootElement name="WF_EVENT_T" namespace="http://xmlns.oracle.com/xdb/APPS/cs.pay.cvs.uploadBill"/>
    </source>
    <source type="WSDL">
      <schema location="../getBillInfo.wsdl"/>
      <rootElement name="getBillInfoInput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getBillInfo"/>
      <param name="getBillInfo_InputVariable.getBillInfoInput_msg" />
    </source>
    <source type="WSDL">
      <schema location="../getBillInfo.wsdl"/>
      <rootElement name="getBillInfoOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getBillInfo"/>
      <param name="getBillInfo_OutputVariable.getBillInfoOutputCollection" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/core/ebs/cs.pay.ebs.Bills_1.0.wsdl"/>
      <rootElement name="uploadBill" namespace="http://www.AlMajdouie.sa/ebs/cs.pay.Bills"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [WED MAY 27 18:31:05 AST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://xmlns.oracle.com/xdb/APPS/cs.pay.cvs.uploadBill"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/cs.pay.application/cs.pay.Bills/getBillInfo"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns3="http://www.AlMajdouie.sa/ebo/util.cmn.EBMHeader"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getBillInfo"
                xmlns:waseu="http://www.AlMajdouie.sa/ebo/util.flt.Fault"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/cs.pay.application/cs.pay.Bills/cs_pay_cvs_uploadBill"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns1="http://www.AlMajdouie.sa/ebs/cs.pay.Bills"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns4="http://www.AlMajdouie.sa/ebo/util.cmn.Basic"
                xmlns:ns2="http://www.AlMajdouie.sa/ebs/cs.pay.Bills/types"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl imp1 ns0 plt wsdl db tns xsd soap12 ns3 soap mime waseu ns1 ns4 ns2 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:param name="getBillInfo_InputVariable.getBillInfoInput_msg"/>
  <xsl:param name="getBillInfo_OutputVariable.getBillInfoOutputCollection"/>
  <xsl:template match="/">
    <ns1:uploadBill>
      <ns1:header>
        <ns3:rquid>
          <xsl:value-of select="$getBillInfo_InputVariable.getBillInfoInput_msg/db:getBillInfoInput/db:reqId"/>
        </ns3:rquid>
      </ns1:header>
      <ns1:body>
        <ns1:requestInformation>
          <ns4:clientDate>
            <xsl:value-of select="substring(/imp1:WF_EVENT_T/SEND_DATE,1,19)"/>
          </ns4:clientDate>
          <ns4:messageCode>
            <xsl:text disable-output-escaping="no">''</xsl:text>
          </ns4:messageCode>
          <ns4:requestUID>
            <xsl:value-of select="$getBillInfo_InputVariable.getBillInfoInput_msg/db:getBillInfoInput/db:reqId"/>
          </ns4:requestUID>
          <ns4:statusCode>
            <xsl:text disable-output-escaping="no">0</xsl:text>
          </ns4:statusCode>
          <ns4:timestamp>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </ns4:timestamp>
        </ns1:requestInformation>
        <ns1:bills>
          <xsl:for-each select="$getBillInfo_OutputVariable.getBillInfoOutputCollection/db:getBillInfoOutputCollection/db:getBillInfoOutput">
            <ns1:billInfo>
              <ns1:officialId>
                <xsl:value-of select="db:CUST_OFFICIAL_ID"/>
              </ns1:officialId>
              <ns1:officailIdType>
                <xsl:value-of select="db:OFFICIAL_ID_TYPE"/>
              </ns1:officailIdType>
              <ns1:serviceType>
                <xsl:text disable-output-escaping="no">''</xsl:text>
              </ns1:serviceType>
              <ns1:billCycle>
                <xsl:value-of select="db:BILL_CYCLE"/>
              </ns1:billCycle>
              <ns1:billingAccount>
                <xsl:value-of select="db:ACCOUNT_NUMBER"/>
              </ns1:billingAccount>
              <ns1:dueAmount>
                <xsl:value-of select="db:BILL_DUES"/>
              </ns1:dueAmount>
              <ns1:dueDate>
                <xsl:value-of select="db:DUE_DATE"/>
              </ns1:dueDate>
              <ns1:expiryDate>
                <xsl:value-of select="db:EXPIRY_DATE"/>
              </ns1:expiryDate>
              <ns1:paymentRanges>
                <ns1:billType>
                  <xsl:value-of select='dvm:lookupValue("billTypeMapping.dvm","OLFMBillType",db:BILL_TYPE,"SOABillType","undefinedBillType")'/>
                </ns1:billType>
                <ns1:range>
                  <ns1:lower>
                    <xsl:value-of select="db:AMOUNT_HI"/>
                  </ns1:lower>
                  <ns1:upper>
                    <xsl:value-of select="db:AMOUNT_LOW"/>
                  </ns1:upper>
                </ns1:range>
              </ns1:paymentRanges>
            </ns1:billInfo>
          </xsl:for-each>
        </ns1:bills>
      </ns1:body>
    </ns1:uploadBill>
  </xsl:template>
</xsl:stylesheet>
