<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../cs_pay_cvs_uploadBill.wsdl"/>
      <rootElement name="WF_EVENT_T" namespace="http://xmlns.oracle.com/xdb/APPS/cs.pay.cvs.uploadBill"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../getBillInfo.wsdl"/>
      <rootElement name="getBillInfoInput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getBillInfo"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [WED MAY 20 15:23:29 AST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:imp1="http://xmlns.oracle.com/xdb/APPS/cs.pay.cvs.uploadBill"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/cs.pay.application/cs.pay.Bills/getBillInfo"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getBillInfo"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/apps/cs.pay.application/cs.pay.Bills/cs_pay_cvs_uploadBill"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl imp1 plt wsdl tns xsd ns0 db aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <db:getBillInfoInput>
      <xsl:for-each select="/imp1:WF_EVENT_T/PARAMETER_LIST/PARAMETER_LIST_ITEM">
        <xsl:choose>
          <xsl:when test='NAME = "REQ_ID"'>
            <db:reqId>
              <xsl:if test="VALUE/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="VALUE/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="VALUE"/>
            </db:reqId>
          </xsl:when>
        </xsl:choose>
      </xsl:for-each>
      <xsl:for-each select="/imp1:WF_EVENT_T/PARAMETER_LIST/PARAMETER_LIST_ITEM">
        <xsl:choose>
          <xsl:when test='NAME = "STATUS_CODE"'>
            <db:statusCode>
              <xsl:if test="VALUE/@xsi:nil">
                <xsl:attribute name="xsi:nil">
                  <xsl:value-of select="VALUE/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="VALUE"/>
            </db:statusCode>
          </xsl:when>
        </xsl:choose>
      </xsl:for-each>
    </db:getBillInfoInput>
  </xsl:template>
</xsl:stylesheet>
