<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../cs.pay.ebs.Accounts_1.0Wrapper.wsdl"/>
      <rootElement name="fault" namespace="http://www.AlMajdouie.sa/ebo/util.flt.Fault"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/core/ebs/cs.pay.ebs.Accounts_1.0.wsdl"/>
      <rootElement name="fault" namespace="http://www.AlMajdouie.sa/ebo/util.flt.Fault"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [WED MAY 20 09:43:34 AST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://www.AlMajdouie.sa/ebs/cs.pay.ebs.Accounts/types"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns0="http://www.AlMajdouie.sa/ebo/util.cmn.EBMHeader"
                xmlns:tns="http://www.AlMajdouie.sa/ebs/cs.pay.ebs.Accounts"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:waseu="http://www.AlMajdouie.sa/ebo/util.flt.Fault"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:wasec="http://www.AlMajdouie.sa/ebs/cs.pay.Accounts"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://www.AlMajdouie.sa/ebo/util.cmn.Basic"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 soap12 ns0 tns soap mime waseu wasec ns2 xsd aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <waseu:fault>
      <waseu:source>
        <xsl:value-of select="/waseu:fault/waseu:source"/>
      </waseu:source>
      <waseu:errorList>
        <xsl:for-each select="/waseu:fault/waseu:errorList/waseu:error">
          <waseu:error>
            <waseu:errorCode>
              <xsl:value-of select="waseu:errorCode"/>
            </waseu:errorCode>
            <waseu:description>
              <xsl:value-of select="waseu:description"/>
            </waseu:description>
          </waseu:error>
        </xsl:for-each>
      </waseu:errorList>
      <xsl:copy-of select="/waseu:fault/waseu:details">
        <?oracle-xsl-mapper-position waseu:details?>
      </xsl:copy-of>
      <ns0:ebmCID>
        <xsl:value-of select="/waseu:fault/ns0:ebmCID"/>
      </ns0:ebmCID>
      <ns0:ebmMID>
        <xsl:value-of select="/waseu:fault/ns0:ebmMID"/>
      </ns0:ebmMID>
      <waseu:faultInstanceId>
        <xsl:value-of select="/waseu:fault/waseu:faultInstanceId"/>
      </waseu:faultInstanceId>
      <waseu:propertySet>
        <xsl:for-each select="/waseu:fault/waseu:propertySet/ns2:property">
          <ns2:property>
            <xsl:attribute name="name">
              <xsl:value-of select="@name"/>
            </xsl:attribute>
            <xsl:if test="ns2:value">
              <xsl:for-each select="ns2:value">
                <ns2:value>
                  <xsl:value-of select="."/>
                </ns2:value>
              </xsl:for-each>
            </xsl:if>
          </ns2:property>
        </xsl:for-each>
      </waseu:propertySet>
      <xsl:if test="/waseu:fault/waseu:timestamp">
        <waseu:timestamp>
          <xsl:value-of select="/waseu:fault/waseu:timestamp"/>
        </waseu:timestamp>
      </xsl:if>
      <xsl:if test="/waseu:fault/waseu:causeList">
        <waseu:causeList>
          <xsl:for-each select="/waseu:fault/waseu:causeList/waseu:cause">
            <waseu:cause>
              <waseu:source>
                <xsl:value-of select="waseu:source"/>
              </waseu:source>
              <waseu:errorList>
                <xsl:for-each select="waseu:errorList/waseu:error">
                  <waseu:error>
                    <waseu:errorCode>
                      <xsl:value-of select="waseu:errorCode"/>
                    </waseu:errorCode>
                    <waseu:description>
                      <xsl:value-of select="waseu:description"/>
                    </waseu:description>
                  </waseu:error>
                </xsl:for-each>
              </waseu:errorList>
              <ns0:ebmCID>
                <xsl:value-of select="ns0:ebmCID"/>
              </ns0:ebmCID>
              <ns0:ebmMID>
                <xsl:value-of select="ns0:ebmMID"/>
              </ns0:ebmMID>
              <waseu:faultInstanceId>
                <xsl:value-of select="waseu:faultInstanceId"/>
              </waseu:faultInstanceId>
              <waseu:propertySet>
                <xsl:for-each select="waseu:propertySet/ns2:property">
                  <ns2:property>
                    <xsl:attribute name="name">
                      <xsl:value-of select="@name"/>
                    </xsl:attribute>
                    <xsl:if test="ns2:value">
                      <xsl:for-each select="ns2:value">
                        <ns2:value>
                          <xsl:value-of select="."/>
                        </ns2:value>
                      </xsl:for-each>
                    </xsl:if>
                  </ns2:property>
                </xsl:for-each>
              </waseu:propertySet>
              <xsl:if test="waseu:timestamp">
                <waseu:timestamp>
                  <xsl:value-of select="waseu:timestamp"/>
                </waseu:timestamp>
              </xsl:if>
            </waseu:cause>
          </xsl:for-each>
        </waseu:causeList>
      </xsl:if>
    </waseu:fault>
  </xsl:template>
</xsl:stylesheet>
