<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/core/ebs/cs.pay.ebs.Bills_1.0.wsdl"/>
      <rootElement name="confirmBill" namespace="http://www.AlMajdouie.sa/ebs/cs.pay.Bills"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../cs.pay.ebs.Bills_1.0Wrapper.wsdl"/>
      <rootElement name="confirmBill" namespace="http://www.AlMajdouie.sa/ebs/cs.pay.Bills"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [SAT MAY 23 11:36:13 AST 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://www.AlMajdouie.sa/ebo/util.cmn.EBMHeader"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:waseu="http://www.AlMajdouie.sa/ebo/util.flt.Fault"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://www.AlMajdouie.sa/ebs/cs.pay.Bills"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns2="http://www.AlMajdouie.sa/ebo/util.cmn.Basic"
                xmlns:ns0="http://www.AlMajdouie.sa/ebs/cs.pay.Bills/types"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl soap12 ns1 soap mime waseu tns ns2 ns0 xsd aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <tns:confirmBill>
      <tns:header>
        <xsl:if test="/tns:confirmBill/tns:header/ns2:localSender">
          <ns2:localSender>
            <xsl:value-of select="/tns:confirmBill/tns:header/ns2:localSender"/>
          </ns2:localSender>
        </xsl:if>
        <ns2:clientDate>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:clientDate"/>
        </ns2:clientDate>
        <ns2:messageCode>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:messageCode"/>
        </ns2:messageCode>
        <ns2:statusCode>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:statusCode"/>
        </ns2:statusCode>
        <ns2:rqUID>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:rqUID"/>
        </ns2:rqUID>
        <ns2:asyncRqUID>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:asyncRqUID"/>
        </ns2:asyncRqUID>
        <ns2:uploadDate>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:uploadDate"/>
        </ns2:uploadDate>
        <ns2:processingDate>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:processingDate"/>
        </ns2:processingDate>
        <ns2:successRecordCount>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:successRecordCount"/>
        </ns2:successRecordCount>
        <ns2:errorRecordCount>
          <xsl:value-of select="/tns:confirmBill/tns:header/ns2:errorRecordCount"/>
        </ns2:errorRecordCount>
        <xsl:if test="/tns:confirmBill/tns:header/ns2:pendingRecordCount">
          <ns2:pendingRecordCount>
            <xsl:value-of select="/tns:confirmBill/tns:header/ns2:pendingRecordCount"/>
          </ns2:pendingRecordCount>
        </xsl:if>
      </tns:header>
      <tns:body>
        <xsl:for-each select="/tns:confirmBill/tns:body/ns2:infoError">
          <ns2:infoError>
            <ns2:error>
              <ns2:errorCode>
                <xsl:value-of select="ns2:error/ns2:errorCode"/>
              </ns2:errorCode>
              <ns2:errorMessage>
                <xsl:value-of select="ns2:error/ns2:errorMessage"/>
              </ns2:errorMessage>
            </ns2:error>
            <ns2:information>
              <ns2:billingAccount>
                <xsl:value-of select="ns2:information/ns2:billingAccount"/>
              </ns2:billingAccount>
              <xsl:if test="ns2:information/ns2:officialId">
                <ns2:officialId>
                  <xsl:value-of select="ns2:information/ns2:officialId"/>
                </ns2:officialId>
              </xsl:if>
              <xsl:if test="ns2:information/ns2:officialIdType">
                <ns2:officialIdType>
                  <xsl:value-of select="ns2:information/ns2:officialIdType"/>
                </ns2:officialIdType>
              </xsl:if>
              <ns2:billerId>
                <xsl:value-of select="ns2:information/ns2:billerId"/>
              </ns2:billerId>
              <ns2:serviceType>
                <xsl:value-of select="ns2:information/ns2:serviceType"/>
              </ns2:serviceType>
              <xsl:if test="ns2:information/ns2:accountStatusCode">
                <ns2:accountStatusCode>
                  <xsl:value-of select="ns2:information/ns2:accountStatusCode"/>
                </ns2:accountStatusCode>
              </xsl:if>
            </ns2:information>
          </ns2:infoError>
        </xsl:for-each>
      </tns:body>
    </tns:confirmBill>
  </xsl:template>
</xsl:stylesheet>
